import * as T from './vendor/three.module.min.js';
import {GLTFLoader} from './vendor/GLTFLoader.js';
import {OrbitControls} from './vendor/OrbitControls.js';
import {RoomEnvironment} from './vendor/RoomEnvironment.js';
import {createEntry} from './entry.js';
const $=id=>document.getElementById(id),renderer=new T.WebGLRenderer({canvas:$('view'),antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;
const scene=new T.Scene();scene.background=new T.Color('#17242b');scene.fog=new T.Fog('#17242b',16,40);const camera=new T.PerspectiveCamera(38,1,.02,100),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.target.set(-.4,1,0);camera.position.set(-7,3.6,5);
const pm=new T.PMREMGenerator(renderer);scene.environment=pm.fromScene(new RoomEnvironment(),.04).texture;scene.add(new T.HemisphereLight(0xcdeaff,0x444039,2));const sun=new T.DirectionalLight(0xffffff,3);sun.position.set(-3,8,4);scene.add(sun);
const floor=new T.Mesh(new T.PlaneGeometry(100,100),new T.MeshStandardMaterial({color:'#26373d',roughness:.95}));floor.rotation.x=-Math.PI/2;floor.position.y=-.01;scene.add(floor);const grid=new T.GridHelper(30,60,0x53605b,0x33474c);grid.position.y=.001;scene.add(grid);
let current='entry',time=0,playing=true,duration=12,mixer,character,skeleton,entry,ground,car,doorAction,doorMixer;const cache=new Map(),loader=new GLTFLoader();let selection=0;
function cameraView(type){const p=type==='inside'?[-2.6,2.1,-.15]:type==='driver'?[-4.8,2.3,1.6]:[-7,3.6,5];camera.position.fromArray(p);controls.target.set(-.55,1.2,-.2);controls.update()}
const catalog=await fetch('./model/catalog.json').then(r=>r.json());for(const c of catalog){const o=document.createElement('option');o.value=c.id;o.textContent='Исходная · '+c.title;$('clip').append(o)}
async function load(id){if(!cache.has(id))cache.set(id,loader.loadAsync('./model/'+id+'.glb'));return cache.get(id)}
try{const g=await load('raptor');car=g.scene;ground=-new T.Box3().setFromObject(car,true).min.y;car.position.y=ground;scene.add(car);doorMixer=new T.AnimationMixer(car);doorAction=doorMixer.clipAction(g.animations.find(c=>c.name==='Object_126Action.001'));doorAction.play();doorAction.paused=true;await choose('entry');$('loading').style.display='none'}catch(e){$('loading').textContent='Ошибка загрузки: '+e.message;throw e}
async function choose(id){const n=++selection;playing=false;$('loading').style.display='block';const g=await load(id==='entry'?'y_bot':id);if(n!==selection)return;if(character)scene.remove(character);if(skeleton){scene.remove(skeleton);skeleton.dispose()}character=g.scene;scene.add(character);current=id;character.position.set(0,0,0);character.rotation.set(0,0,0);car.visible=id==='entry';mixer=new T.AnimationMixer(character);if(id==='entry'){entry=createEntry(character,ground);duration=12;$('description').textContent='Авторская скелетная постановка · IK рук и ног · прототип'}else{const action=mixer.clipAction(g.animations[0]);action.play();action.paused=true;duration=g.animations[0].duration;character.position.x=-.5;$('description').textContent=catalog.find(c=>c.id===id).source+' · без замены исходного движения'}skeleton=new T.SkeletonHelper(character);skeleton.visible=$('bones').checked;scene.add(skeleton);time=0;$('time').max=duration;playing=true;$('play').textContent='Пауза';$('loading').style.display='none';apply()}
function apply(){if(!character)return;if(current==='entry'){const p=entry(time);doorAction.time=p.door*doorAction.getClip().duration;doorMixer.update(0);$('phase').textContent=p.label}else{const a=mixer.existingAction(mixer._actions[0]._clip);a.time=time;mixer.update(0);$('phase').textContent='SOURCE / '+catalog.find(c=>c.id===current).title}scene.updateMatrixWorld(true);$('time').value=time;$('clock').textContent=time.toFixed(2)+' / '+duration.toFixed(2)}
$('clip').onchange=()=>choose($('clip').value).catch(e=>{$('loading').textContent=e.message});$('play').onclick=()=>{if(time>=duration)time=0;playing=!playing;$('play').textContent=playing?'Пауза':'Играть'};$('time').oninput=()=>{playing=false;$('play').textContent='Играть';time=+$('time').value;apply()};for(const id of ['outside','driver','inside'])$(id).onclick=()=>cameraView(id);$('bones').onchange=()=>skeleton.visible=$('bones').checked;
const materials=new Map();car.traverse(o=>{if(o.isMesh)for(const m of Array.isArray(o.material)?o.material:[o.material])if(!materials.has(m))materials.set(m,[m.opacity,m.transparent,m.depthWrite])});$('xray').onchange=()=>{for(const [m,orig]of materials){[m.opacity,m.transparent,m.depthWrite]=$('xray').checked?[.17,true,false]:orig;m.needsUpdate=true}};
const clock=new T.Clock();renderer.setAnimationLoop(()=>{const dt=Math.min(clock.getDelta(),.1);if(playing){time+=dt*+$('speed').value;if(time>duration){if($('loop').checked)time%=duration;else{time=duration;playing=false;$('play').textContent='Играть'}}apply()}const w=$('view').clientWidth,h=$('view').clientHeight;if(renderer.domElement.width!==Math.floor(w*renderer.getPixelRatio())||renderer.domElement.height!==Math.floor(h*renderer.getPixelRatio())){renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}controls.update();renderer.render(scene,camera)});
window.lab={setTime(t){playing=false;time=T.MathUtils.clamp(t,0,duration);apply()},choose,get character(){return character},get car(){return car},get scene(){return scene},get camera(){return camera},get ground(){return ground},cameraView};
